apiVersion: v1
kind: Secret
metadata:
  name: vehicle-backend-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==   # Benutzername "root" (Base64-codiert)
  SPRING_DATASOURCE_PASSWORD: cm9vdA==   # Passwort "root" (Base64-codiert)