apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-backend  # Name des Deployments
spec:
  replicas: 1  # Anzahl der gew체nschten Pods
  selector:
    matchLabels:
      app: vehicle-backend  # Label-Selector f체r die Pods
  template:
    metadata:
      labels:
        app: vehicle-backend  # Label f체r die Pods
    spec:
      containers:
        - name: commercial-vehicles-backend-app  # Name des Containers
          image: nmenfaa/commercial-vehicles-backend-app:latest  # Verwendetes Docker-Image aus Docker Hub
          ports:
            - containerPort: 8080  # Port, auf dem die App im Container l채uft
          envFrom:
            - configMapRef:
                name: vehicle-backend-env
            - secretRef:
                name: vehicle-backend-secret